# Generated by Django 6.0.2 on 2026-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overall_progress',
            field=models.IntegerField(default=0),
        ),
    ]
