# Generated by Django 6.0.2 on 2026-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_overall_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.CharField(
                choices=[
                    ("#4F46E5", "Indigo"),
                    ("#10B981", "Emerald"),
                    ("#F59E0B", "Amber"),
                    ("#EF4444", "Rose"),
                    ("#8B5CF6", "Violet"),
                    ("#06B6D4", "Cyan"),
                    ("#EC4899", "Pink"),
                ],
                default="#4F46E5",
                max_length=7,
            ),
        ),
    ]
