# Generated by Django 6.0.2 on 2026-02-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('developer', 'Developer'), ('observer', 'Observer (View Only)')], default='developer', max_length=20),
        ),
    ]
