# Generated by Django 6.0.2 on 2026-02-28 06:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('blocked', 'Blocked')], db_index=True, default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resource'),
        ),
    ]
