# Generated by Django 6.0.2 on 2026-02-28 06:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resource'),
        ),
    ]
