# Generated by Django 6.0.2 on 2026-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_taskattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="change_request_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="change_request_type",
            field=models.CharField(
                blank=True,
                choices=[("MAJOR", "MAJOR"), ("MINOR", "MINOR")],
                max_length=10,
                null=True,
            ),
        ),
    ]
