# Generated by Django 6.0.2 on 2026-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_change_request_no_task_change_request_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="days",
            field=models.PositiveIntegerField(
                default=1, help_text="Total number of days allocated for this task"
            ),
        ),
    ]
