# Generated by Django 6.0.2 on 2026-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_task_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="display_id",
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
