# Generated by Django 6.0.2 on 2026-03-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_display_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="days",
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
