# Generated by Django 6.0.2 on 2026-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_task_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed before this task can start.",
                related_name="blocked_tasks",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="dependency_remark",
            field=models.TextField(
                blank=True,
                help_text="Reason for the dependency (e.g., 'Waiting for Task 6 API')",
                null=True,
            ),
        ),
    ]
