# Generated by Django 6.0.2 on 2026-03-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status_alter_taskattachment_file'),
        ('tasks', '0011_task_dependencies_task_dependency_remark'),
    ]

    operations = [
    ]
