# Generated by Django 6.0.2 on 2026-03-31 08:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_merge_20260310_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='auto'),
        ),
    ]
